### ISSUE TITLE
Feature Request: string shortening

### ISSUE THREAD

**Issue by CamdenFoucht** [uiwjs/react-json-view#12]
It would be great if we could have some prop like `shortenTextAfterLength` to shorten long JSON strings after a desired length:

```
my not very long long string example
```

providing `shortenTextAfterLength` to `10` would render

```
my not very...
```

with the ability for users to expand/collapse the string. This would give a much better view for JSON objects that might have strings that are 1000+ characters long

**Comment by jaywcjlove** [comment]
@CamdenFoucht Upgrade `v1.9.0`

https://github.com/uiwjs/react-json-view/blob/9c03a58d97b070c6f0d315d0e3e4ca79e1074e23/core/src/index.tsx#L43-L44

**Comment by CamdenFoucht** [comment]
Wow that was fast! Thank you, that is perfect!
