### ISSUE TITLE
Support for Map/Set

### ISSUE THREAD

**Issue by mkdynamic** [uiwjs/react-json-view#13]
`Map` and `Set` objects appear blank currently.

**Comment by jaywcjlove** [comment]
@mkdynamic After editing it may become an object , I tried to implement it

**Comment by jaywcjlove** [comment]
@mkdynamic Upgrade `v1.12.0`

**Comment by mkdynamic** [comment]
Wow, that was fast! Awesome 🎉

**Comment by mkdynamic** [comment]
Fixed!
