### ISSUE TITLE
react should be a peer dependency

### ISSUE THREAD

**Issue by chiptus** [uiwjs/react-json-view#28]
since this library relies on useId, it means it depends on react@18, should state it somewhere.

**Comment by chiptus** [comment]
it has it, sorry

**Comment by maksymkp** [comment]
> since this library relies on useId, it means it depends on react@18, should state it somewhere.

with all respect, it seems an overkill to include the "whole" react dependency for random id generation. Wouldn't it make more sense to find a dedicate package for random id instead?
