### ISSUE TITLE
Editing JSON

### ISSUE THREAD

**Issue by jack-michaud** [uiwjs/react-json-view#3]
The README says:

> A React component for displaying and **editing** javascript arrays and JSON objects.

However, there is no way to edit the provided JSON. There doesn't seem to be an example in the README or properties on the JsonView component for this. Was it a mistake to include this in the README? This library does a great job of displaying JSON, but it's misleading to state that it also does editing. 

Thanks for your time!

**Comment by jaywcjlove** [comment]
@jack-michaud Components are released for 4 days only. Editing functionality is one of our goals and is currently being planned.
