### ISSUE TITLE
Is it possible to make the copy-button always show on the same line?

### ISSUE THREAD

**Issue by globetro** [uiwjs/react-json-view#33]
On slightly longer lines, the copy button will wrap to a newline which causes the rest of the JSON to shift down, which is a bit annoying to work with.

**Comment by globetro** [comment]
Actually I think this is a bug as your examples the copy is always on same line. I could fix it if I added `display: flex` to w-rjv-line

**Comment by jaywcjlove** [comment]
@globetro I'm not sure what the issue is; adding `display: flex` doesn't seem to resolve anything.

**Comment by globetro** [comment]
Are you having the same issue as me and display: flex didn't fix it?

**Comment by jaywcjlove** [comment]
@globetro I didn't find any issues. Could you provide a reproducible example for reference?

**Comment by olavim** [comment]
For me the issue was Next.js setting `display: block` for svg elements by default.

**Comment by jaywcjlove** [comment]
@olavim thx! I have reproduced this issue.  upgrade `v2.0.0-alpha.15` @globetro

**Comment by jaywcjlove** [comment]
@globetro @olavim upgrade `2.0.0-alpha.16`

**Comment by globetro** [comment]
Thank you that fixed it!

**Comment by daryllimyt** [comment]
how can I fix this in V1 with tailwind+nextjs? I want to use this with the editor feature but if I'm not mistaken V2 doesn't have editor support yet.
