### ISSUE TITLE
Item counts always show up as plural

### ISSUE THREAD

**Issue by esilverm** [uiwjs/react-json-view#39]
When only one item appears in an collection, the item count reads "1 items" which is grammatically incorrect. It should instead read "1 item".

![Screenshot 2024-03-14 at 2 27 49 PM](https://github.com/uiwjs/react-json-view/assets/24704789/00c96d21-889c-434a-b73b-4211811fe7a6)

**Comment by jaywcjlove** [comment]
@esilverm thx! upgrade `v2.0.0-alpha.20`
