### ISSUE TITLE
"Uncaught TypeError: Do not know how to serialize a BigInt"

### ISSUE THREAD

**Issue by gregfenton** [uiwjs/react-json-view#42]
Using the example currently posted to [the homepage](https://uiwjs.github.io/react-json-view/):

1. open the browser's DevTools >> Console
2. click the "copy to clipboard" icon for the top-most node (see image)

EXPECTED:
- data of the whole JSON object is copied to clipboard

ACTUAL:
- exception displays in Console and nothing is copied to clipboard

![image](https://github.com/uiwjs/react-json-view/assets/4407559/60a52274-19a8-4d7e-8aaa-212b388c4194)

**Comment by gregfenton** [comment]
I wonder if on [this line](https://github.com/uiwjs/react-json-view/blob/d98d1c1b347793cdfe78a2da523bcd5a62de25df/core/src/comps/Copied.tsx#L40) the code should be something more like:

```js
copyText = JSON.stringify(value, (_, v) => typeof v === 'bigint' ? v.toString() : v, 2);
```

as per [this SO answer](https://stackoverflow.com/a/65156250/229326).

There does not seem to be a really good way to deal with "BigInt" in JSON, as [this other answer](https://stackoverflow.com/a/77969073/229326) on that same SO post outlines in great detail.

**Comment by gregfenton** [comment]
@jaywcjlove did you see my recommendation above about creating a utility function?

**Comment by jaywcjlove** [comment]
The current team only has me actively maintaining. However, due to the large number of Git repositories I oversee, I couldn't see your PR in time. Just saw it now, and I think it's fine, so I've merged and released a new version.

@gregfenton Thx!

**Comment by gregfenton** [comment]
If you want to point me to how you do utils, I'm happy to do another PR.

**Comment by gregfenton** [comment]
PR merged

**Comment by jaywcjlove** [comment]
@gregfenton I would be very happy to see another PR from you.
