### ISSUE TITLE
navigator.clipboard is undefined

### ISSUE THREAD

**Issue by Gao-pw** [uiwjs/react-json-view#55]
![图片](https://github.com/user-attachments/assets/905602c1-add0-4f81-afed-ae81f8163cc3)

Navigator.clipboard cannot be used normally in non-https environments. Is this intentionally designed like this? Is there a compatible method? If so, I can provide a pr.

**Comment by jaywcjlove** [comment]
@Gao-pw  It was not intentional. You're welcome to submit a PR to fix this issue.

**Comment by Gao-pw** [comment]
> @Gao-pw It was not intentional. You're welcome to submit a PR to fix this issue.

👋pr is here #56

**Comment by jaywcjlove** [comment]
@Gao-pw thx! upgrade `v2.0.0-alpha.26`

**Comment by Gao-pw** [comment]
😃
