### ISSUE TITLE
对于Map这种数据结构，如果Key是一个对象，有办法在预览的时候显示吗？

### ISSUE THREAD

**Issue by MilesPan** [uiwjs/react-json-view#57]
`const map = new Map(); map.set({ name: 1 }, 10); map.set({ name: 2 }, 10);`
`<ReactJson value={{ map, key: 1 }} style={jsonTheme}></ReactJson>`
目前预览效果是这样的。
![image](https://github.com/user-attachments/assets/9887c152-b1ca-41e8-9886-f0ad95db16e1)

期望：
有没有办法实现DevTool中这种预览效果
![image](https://github.com/user-attachments/assets/ac10ab56-477c-4786-99ac-aed5e5b6ce9f)

**Comment by jaywcjlove** [comment]
@MilesPan 样式可以定义出来，但是你可以自己研究一下，参考官方示例

https://github.com/uiwjs/react-json-view/blob/32b34c1b57a73e9cb46022aea406110b89cb79cb/www/src/example/default.tsx#L25-L68

<img width="907" alt="image" src="https://github.com/user-attachments/assets/2c995493-5086-407c-a1f7-628183e9c340">
