### ISSUE TITLE
JsonView.KeyName invalid path to root in `keys`

### ISSUE THREAD

**Issue by sebastiaan-dev** [uiwjs/react-json-view#61]
I am using the `keys` prop to locate the current item during selection. For this to work I need the path from the root to the selected item. However, whenever I select something of `NestedOpen` type it only gives the current key as the path.

At first I thought to add the `keys` prop as below in `NestedOpen.tsx:51`:

```tsx
<KayName keyName={keyName} keys={keys} />
```

But this still gave only a single key. It seems it finds the full path when rendering for the first time, but forgets on subsequent renders. Hope you can help!

Best Regards

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-json-view/blob/3208d8269950a17463b9688dc9d7bac9af89aae5/core/src/comps/NestedOpen.tsx#L51

@sebastiaan-dev  It seems that I have fixed this issue. Please confirm.

**Comment by sebastiaan-dev** [comment]
Yes it works! Thank you for the quick fix!
