### ISSUE TITLE
Babel _interopRequireDefault is not a function

### ISSUE THREAD

**Issue by maxxlwr** [uiwjs/react-json-view#7]
Hey! Thanks for your project.
Just found an issue when I try to test my app. I use Jest with SWC transformer.

<img width="933" alt="image" src="https://github.com/uiwjs/react-json-view/assets/37516683/cf7190b8-5ab3-4c71-8ce2-40205a273432">

I also tried in another Vite app, and when I serve it locally, I can see other babel issues
<img width="732" alt="image" src="https://github.com/uiwjs/react-json-view/assets/37516683/d7c09269-b291-4da5-8617-1ca31fc3a16a">

Could you please take a look at it? Thanks

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-json-view/blob/801ae40f9285e8fba57f1fe6f8913e6640e771e5/core/package.json#L48

@maxxlwr After add `@babel/runtime`, I fixed it
